project:
  type: website
  output-dir: build
  resources:
    - "Exploring_and_Visualizing_27’714_Aircraft Designs_Berdelis_Aziz_DS25a.pptx"
  render:
    - index.qmd
    - project_charta.qmd
    - data_report.qmd
    - meeting_notes.qmd

lang: en
language:
  section-title-appendices: "Appendix"

website:
  title: "Exploring and Visualizing 27’714 Aircraft Designs"
  search: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - project_charta.qmd
      - data_report.qmd
      - meeting_notes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
      

number-sections: true

bibliography: refs.bib
csl: vancouver-brackets.csl

jupyter: python3

execute:
  freeze: auto

editor:
  render-on-save: true
